<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 D:\Node\svelte-craft\static\models\unit.glb --root /models/ --types --printwidth 120 --precision 2 --transform --resolution 1024
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      Unit: THREE.Mesh
      PowerPlant: THREE.Mesh
      Citidel: THREE.Mesh
      SupplyDepot: THREE.Mesh
    }
    materials: {}
  }

  const gltf = useGltf<GLTFResult>('/models/unit-transformed.glb', { useDraco: true })

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh geometry={gltf.nodes.Unit.geometry} material={gltf.nodes.Unit.material} position={[0, 1.43, 0]} />
    <T.Mesh geometry={gltf.nodes.PowerPlant.geometry} material={gltf.nodes.PowerPlant.material} />
    <T.Mesh geometry={gltf.nodes.Citidel.geometry} material={gltf.nodes.Citidel.material} />
    <T.Mesh geometry={gltf.nodes.SupplyDepot.geometry} material={gltf.nodes.SupplyDepot.material} />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
